data:
  raw_data_path: data/raw/train.csv
  processed_data_path: data/processed/

model:
  test_size: 0.2
  random_state: 42

training:
  target_column: Sales

mlflow:
  experiment_name: retail_forecasting

data:
  train_path: data/raw/train.csv
  store_path: data/raw/store.csv
  processed_path: data/processed/master_dataset.csv

logging:
  log_file: logs/project.log